hubspot_lakehouse:
  outputs:
    dev:
      type: duckdb
      path: dev.db
      threads: 1
      extensions:
        - azure
        - httpfs
      settings:
        secret_directory: ~/.duckdb/stored_secrets

  target: dev
