version: '3.8'

services:
  unity-catalog:
    image: unitycatalog/unitycatalog:latest
    platform: linux/amd64  # Force x86_64 platform for compatibility
    container_name: unity-catalog
    ports:
      - "8080:8080"  # Unity Catalog API
    environment:
      - AZURE_STORAGE_ACCOUNT=strprimrosedatalake
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - UNITY_CATALOG_HOST=0.0.0.0
      - UNITY_CATALOG_PORT=8080
    volumes:
      - type: volume
        source: unitycatalog_data
        target: /opt/unitycatalog/etc/data
      - type: bind
        source: ./config/unity-catalog/server.properties
        target: /home/unitycatalog/etc/conf/server.properties
        read_only: true
    networks:
      - lakehouse_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 60s
      timeout: 10s
      retries: 3

  duckdb:
    image: duckdb/duckdb:latest
    platform: linux/amd64
    container_name: duckdb
    ports:
      - "8081:8081"  # DuckDB HTTP API
      - "8082:8082"  # DuckDB Web UI (if available)
    environment:
      - UNITY_CATALOG_URL=http://unity-catalog:8080
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - DUCKDB_HTTP_PORT=8081
      - DUCKDB_WEB_PORT=8082
    depends_on:
      unity-catalog:
        condition: service_healthy
    volumes:
      - ./config/duckdb:/app/config
      - ./scripts/init-duckdb.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - lakehouse_network
    command: >
      sh -c "
        echo 'Installing extensions...' &&
        duckdb --http --http-port 8081 --http-host 0.0.0.0 &&
        echo 'DuckDB HTTP server started on port 8081'
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # dbt-core:
  #   image: ghcr.io/dbt-labs/dbt-core:latest
  #   platform: linux/amd64
  #   container_name: dbt-core
  #   volumes:
  #     - ./dbt:/dbt
  #     - dbt_models:/dbt/models
  #     - ./config/dbt:/dbt/config
  #   environment:
  #     - DUCKDB_DATABASE=:memory:
  #     - UNITY_CATALOG_URL=http://unity-catalog:8080
  #     - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
  #     - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
  #   working_dir: /dbt
  #   depends_on:
  #     unity-catalog:
  #       condition: service_healthy
  #     duckdb:
  #       condition: service_healthy
  #   networks:
  #     - lakehouse_network
  #   command: tail -f /dev/null

volumes:
  unitycatalog_data:
  dbt_models:
    driver: local

networks:
  lakehouse_network:
    driver: bridge 