version: '3.8'

services:
  unity-catalog:
    image: unitycatalog/unitycatalog:latest
    platform: linux/amd64  # Force x86_64 platform for compatibility
    container_name: unity-catalog
    ports:
      - "8080:8080"  # Unity Catalog API
    environment:
      - AZURE_STORAGE_ACCOUNT=strprimrosedatalake
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - UNITY_CATALOG_HOST=0.0.0.0
      - UNITY_CATALOG_PORT=8080
    volumes:
      - type: volume
        source: unitycatalog_data
        target: /opt/unitycatalog/etc/data
    networks:
      - lakehouse_network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    # command: ["tail", "-f", "/dev/null"]  # Placeholder command
  
  # unity-catalog-ui:
  #   build:
  #     context: ui/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - unity-catalog-server

  duckdb:
    image: datacatering/duckdb:v1.3.0
    platform: linux/amd64  # Force x86_64 platform for compatibility
    container_name: duckdb
    ports:
      - "8081:8081"  # DuckDB HTTP API
    environment:
      - UNITY_CATALOG_URL=http://unity-catalog:8080
      - DUCKDB_HTTP_PORT=8081
    depends_on:
      unity-catalog:
        condition: service_healthy
    volumes:
      - ./config/duckdb:/app/config
    networks:
      - lakehouse_network
    command: ["duckdb", "--http", "--http-port", "8081"]

  dbt:
    # Using the official dbt-core image with a specific version
    image: ghcr.io/dbt-labs/dbt-core:1.7.0
    platform: linux/amd64  # Force x86_64 platform for compatibility
    container_name: dbt-core
    volumes:
      - ./dbt:/dbt
      - dbt_models:/dbt/models
      - ./config/dbt:/dbt/config
    environment:
      - "DUCKDB_DATABASE=:memory:"
      - UNITY_CATALOG_URL=http://unity-catalog:8080
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
    working_dir: /dbt
    depends_on:
      unity-catalog:
        condition: service_healthy
      duckdb:
        condition: service_started
    networks:
      - lakehouse_network
    command: tail -f /dev/null

volumes:
  unitycatalog_data:
  dbt_models:
    driver: local

networks:
  lakehouse_network:
    driver: bridge 